/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Health: () => import('#controllers/health_controller'),
  Me: () => import('#controllers/me_controller'),
}
