/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Budgets: () => import('#controllers/budgets_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Health: () => import('#controllers/health_controller'),
  Me: () => import('#controllers/me_controller'),
  People: () => import('#controllers/people_controller'),
  Recurring: () => import('#controllers/recurring_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
}
