"""Subsets the Material Symbols Rounded variable font to the icons HisaabChat uses.

Why: the full font is ~14 MB (plus Outlined and Sharp when using the
material_symbols_icons package). Debug web builds can't tree-shake fonts, so the
app took minutes to show its first frame. The subset keeps every variation axis
(FILL, GRAD, opsz, wght), so animated outline -> filled icons still work.

Usage (from the app/ folder):
    pip install fonttools
    python tool/icons/generate_icons.py "path/to/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf" "path/to/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].codepoints"

Source font and .codepoints file: https://github.com/google/material-design-icons/tree/master/variablefont
(Apache License 2.0). The codepoints file is needed because several icon names share
one glyph (e.g. smartphone). The material_symbols_icons package's
iconname_to_unicode_map.dart works as the codepoints file too.
"""

import pathlib
import re
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

APP_DIR = pathlib.Path(__file__).resolve().parents[2]
ICON_LIST = APP_DIR / 'tool' / 'icons' / 'icons.txt'
FONT_OUT = APP_DIR / 'assets' / 'fonts' / 'MaterialSymbolsRounded.ttf'
DART_OUT = APP_DIR / 'lib' / 'core' / 'icons' / 'symbols.g.dart'
FONT_FAMILY = 'MaterialSymbolsRounded'


def read_icon_names() -> list[str]:
    names = []
    for line in ICON_LIST.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if line and not line.startswith('#') and line not in names:
            names.append(line)
    return names


def dart_identifier(name: str) -> str:
    """two_wheeler -> twoWheeler; 3d_rotation -> i3dRotation."""
    parts = name.split('_')
    ident = parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])
    if re.match(r'^\d', ident):
        ident = 'i' + ident
    return ident


def read_codepoints(path: pathlib.Path) -> dict[str, int]:
    """Parses Google's .codepoints file ("name hex") or the package's Dart map ('name': 0xhex)."""
    text = path.read_text(encoding='utf-8')
    pairs = re.findall(r"^(\w+) ([0-9a-f]+)$", text, re.MULTILINE)
    pairs += re.findall(r"'(\w+)': 0x([0-9a-f]+)", text)
    return {name: int(hex_cp, 16) for name, hex_cp in pairs}


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    source = pathlib.Path(sys.argv[1])
    known = read_codepoints(pathlib.Path(sys.argv[2]))

    names = read_icon_names()
    font_cmap = TTFont(source, lazy=True).getBestCmap()
    missing = [n for n in names if n not in known or known[n] not in font_cmap]
    if missing:
        sys.exit(f'Unknown icon names: {", ".join(missing)}')
    codepoints = {name: known[name] for name in names}

    options = subset.Options()
    options.layout_features = []  # codepoints only; no ligatures needed
    options.hinting = False
    options.name_IDs = ['*']
    options.notdef_outline = True
    subsetter = subset.Subsetter(options)
    full = TTFont(source)
    subsetter.populate(unicodes=codepoints.values())
    subsetter.subset(full)
    FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
    full.save(FONT_OUT)

    lines = [
        '// GENERATED by tool/icons/generate_icons.py from tool/icons/icons.txt. DO NOT EDIT.',
        '// ignore_for_file: constant_identifier_names',
        '',
        "import 'package:flutter/widgets.dart';",
        '',
        '/// Material Symbols Rounded glyphs bundled in assets/fonts (variable font:',
        '/// FILL, GRAD, opsz, wght). Use through [AppIcons] rather than directly.',
        'abstract final class Symbols {',
    ]
    for name in names:
        lines.append(
            f"  static const IconData {dart_identifier(name)} = "
            f"IconData(0x{codepoints[name]:x}, fontFamily: '{FONT_FAMILY}');"
        )
    lines.append('')
    lines.append('  /// Icon name (as stored in the database) to glyph.')
    lines.append('  static const Map<String, IconData> byName = {')
    for name in names:
        lines.append(f"    '{name}': {dart_identifier(name)},")
    lines.append('  };')
    lines.append('}')
    DART_OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')

    size_kb = FONT_OUT.stat().st_size / 1024
    print(f'{len(names)} icons -> {FONT_OUT.relative_to(APP_DIR)} ({size_kb:.0f} KB), {DART_OUT.relative_to(APP_DIR)}')


if __name__ == '__main__':
    main()
