// GENERATED by tool/icons/generate_icons.py from tool/icons/icons.txt. DO NOT EDIT.
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

/// Material Symbols Rounded glyphs bundled in assets/fonts (variable font:
/// FILL, GRAD, opsz, wght). Use through [AppIcons] rather than directly.
abstract final class Symbols {
  static const IconData home = IconData(0xe9b2, fontFamily: 'MaterialSymbolsRounded');
  static const IconData receiptLong = IconData(0xef6e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData donutLarge = IconData(0xe917, fontFamily: 'MaterialSymbolsRounded');
  static const IconData accountBalanceWallet = IconData(0xe850, fontFamily: 'MaterialSymbolsRounded');
  static const IconData barChart = IconData(0xe26b, fontFamily: 'MaterialSymbolsRounded');
  static const IconData settings = IconData(0xe8b8, fontFamily: 'MaterialSymbolsRounded');
  static const IconData search = IconData(0xef7a, fontFamily: 'MaterialSymbolsRounded');
  static const IconData moreVert = IconData(0xe5d4, fontFamily: 'MaterialSymbolsRounded');
  static const IconData arrowBack = IconData(0xe5c4, fontFamily: 'MaterialSymbolsRounded');
  static const IconData arrowForward = IconData(0xe5c8, fontFamily: 'MaterialSymbolsRounded');
  static const IconData close = IconData(0xe5cd, fontFamily: 'MaterialSymbolsRounded');
  static const IconData add = IconData(0xe145, fontFamily: 'MaterialSymbolsRounded');
  static const IconData addCard = IconData(0xeb86, fontFamily: 'MaterialSymbolsRounded');
  static const IconData addChart = IconData(0xef3c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData filterList = IconData(0xe152, fontFamily: 'MaterialSymbolsRounded');
  static const IconData calendarMonth = IconData(0xebcc, fontFamily: 'MaterialSymbolsRounded');
  static const IconData edit = IconData(0xf097, fontFamily: 'MaterialSymbolsRounded');
  static const IconData delete = IconData(0xe92e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData contentCopy = IconData(0xe14d, fontFamily: 'MaterialSymbolsRounded');
  static const IconData pushPin = IconData(0xf10d, fontFamily: 'MaterialSymbolsRounded');
  static const IconData archive = IconData(0xe149, fontFamily: 'MaterialSymbolsRounded');
  static const IconData download = IconData(0xf090, fontFamily: 'MaterialSymbolsRounded');
  static const IconData share = IconData(0xe80d, fontFamily: 'MaterialSymbolsRounded');
  static const IconData refresh = IconData(0xe5d5, fontFamily: 'MaterialSymbolsRounded');
  static const IconData chevronRight = IconData(0xe5cc, fontFamily: 'MaterialSymbolsRounded');
  static const IconData check = IconData(0xe668, fontFamily: 'MaterialSymbolsRounded');
  static const IconData groups = IconData(0xf233, fontFamily: 'MaterialSymbolsRounded');
  static const IconData northEast = IconData(0xf1e1, fontFamily: 'MaterialSymbolsRounded');
  static const IconData southWest = IconData(0xf1e5, fontFamily: 'MaterialSymbolsRounded');
  static const IconData swapHoriz = IconData(0xe8d4, fontFamily: 'MaterialSymbolsRounded');
  static const IconData tune = IconData(0xe429, fontFamily: 'MaterialSymbolsRounded');
  static const IconData autorenew = IconData(0xe863, fontFamily: 'MaterialSymbolsRounded');
  static const IconData schedule = IconData(0xefd6, fontFamily: 'MaterialSymbolsRounded');
  static const IconData done = IconData(0xe876, fontFamily: 'MaterialSymbolsRounded');
  static const IconData doneAll = IconData(0xe877, fontFamily: 'MaterialSymbolsRounded');
  static const IconData error = IconData(0xf8b6, fontFamily: 'MaterialSymbolsRounded');
  static const IconData checkCircle = IconData(0xf0be, fontFamily: 'MaterialSymbolsRounded');
  static const IconData warning = IconData(0xf083, fontFamily: 'MaterialSymbolsRounded');
  static const IconData info = IconData(0xe88e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData cloudDone = IconData(0xe2bf, fontFamily: 'MaterialSymbolsRounded');
  static const IconData cloudOff = IconData(0xe2c1, fontFamily: 'MaterialSymbolsRounded');
  static const IconData remove = IconData(0xe15b, fontFamily: 'MaterialSymbolsRounded');
  static const IconData attachFile = IconData(0xe226, fontFamily: 'MaterialSymbolsRounded');
  static const IconData send = IconData(0xe163, fontFamily: 'MaterialSymbolsRounded');
  static const IconData keyboardDoubleArrowDown = IconData(0xead0, fontFamily: 'MaterialSymbolsRounded');
  static const IconData mail = IconData(0xe159, fontFamily: 'MaterialSymbolsRounded');
  static const IconData lock = IconData(0xe899, fontFamily: 'MaterialSymbolsRounded');
  static const IconData visibility = IconData(0xe8f4, fontFamily: 'MaterialSymbolsRounded');
  static const IconData visibilityOff = IconData(0xe8f5, fontFamily: 'MaterialSymbolsRounded');
  static const IconData person = IconData(0xf0d3, fontFamily: 'MaterialSymbolsRounded');
  static const IconData badge = IconData(0xea67, fontFamily: 'MaterialSymbolsRounded');
  static const IconData sell = IconData(0xf05b, fontFamily: 'MaterialSymbolsRounded');
  static const IconData palette = IconData(0xe40a, fontFamily: 'MaterialSymbolsRounded');
  static const IconData database = IconData(0xf20e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData help = IconData(0xe8fd, fontFamily: 'MaterialSymbolsRounded');
  static const IconData logout = IconData(0xe9ba, fontFamily: 'MaterialSymbolsRounded');
  static const IconData devices = IconData(0xe326, fontFamily: 'MaterialSymbolsRounded');
  static const IconData currencyRupee = IconData(0xeaf7, fontFamily: 'MaterialSymbolsRounded');
  static const IconData public = IconData(0xe80b, fontFamily: 'MaterialSymbolsRounded');
  static const IconData event = IconData(0xe878, fontFamily: 'MaterialSymbolsRounded');
  static const IconData brightnessAuto = IconData(0xe1ab, fontFamily: 'MaterialSymbolsRounded');
  static const IconData lightMode = IconData(0xe518, fontFamily: 'MaterialSymbolsRounded');
  static const IconData darkMode = IconData(0xe51c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData animation = IconData(0xe71c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData lockPerson = IconData(0xf8f3, fontFamily: 'MaterialSymbolsRounded');
  static const IconData payments = IconData(0xef63, fontFamily: 'MaterialSymbolsRounded');
  static const IconData accountBalance = IconData(0xe84f, fontFamily: 'MaterialSymbolsRounded');
  static const IconData smartphone = IconData(0xe7ba, fontFamily: 'MaterialSymbolsRounded');
  static const IconData creditCard = IconData(0xe8a1, fontFamily: 'MaterialSymbolsRounded');
  static const IconData savings = IconData(0xe2eb, fontFamily: 'MaterialSymbolsRounded');
  static const IconData wallet = IconData(0xf8ff, fontFamily: 'MaterialSymbolsRounded');
  static const IconData shoppingCart = IconData(0xe8cc, fontFamily: 'MaterialSymbolsRounded');
  static const IconData restaurant = IconData(0xe56c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData twoWheeler = IconData(0xe9f9, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localGasStation = IconData(0xe546, fontFamily: 'MaterialSymbolsRounded');
  static const IconData build = IconData(0xf8cd, fontFamily: 'MaterialSymbolsRounded');
  static const IconData school = IconData(0xe80c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData bolt = IconData(0xea0b, fontFamily: 'MaterialSymbolsRounded');
  static const IconData wifi = IconData(0xe63e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData shoppingBag = IconData(0xf1cc, fontFamily: 'MaterialSymbolsRounded');
  static const IconData medicalServices = IconData(0xf109, fontFamily: 'MaterialSymbolsRounded');
  static const IconData movie = IconData(0xe684, fontFamily: 'MaterialSymbolsRounded');
  static const IconData flight = IconData(0xe539, fontFamily: 'MaterialSymbolsRounded');
  static const IconData spa = IconData(0xeb4c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData redeem = IconData(0xe8f6, fontFamily: 'MaterialSymbolsRounded');
  static const IconData moreHoriz = IconData(0xe5d3, fontFamily: 'MaterialSymbolsRounded');
  static const IconData work = IconData(0xe943, fontFamily: 'MaterialSymbolsRounded');
  static const IconData laptopMac = IconData(0xe320, fontFamily: 'MaterialSymbolsRounded');
  static const IconData familyRestroom = IconData(0xf1a2, fontFamily: 'MaterialSymbolsRounded');
  static const IconData percent = IconData(0xeb58, fontFamily: 'MaterialSymbolsRounded');
  static const IconData undo = IconData(0xe166, fontFamily: 'MaterialSymbolsRounded');
  static const IconData addCircle = IconData(0xe990, fontFamily: 'MaterialSymbolsRounded');
  static const IconData category = IconData(0xe72c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData today = IconData(0xe8df, fontFamily: 'MaterialSymbolsRounded');
  static const IconData history = IconData(0xe8b3, fontFamily: 'MaterialSymbolsRounded');
  static const IconData notes = IconData(0xe26c, fontFamily: 'MaterialSymbolsRounded');
  static const IconData balance = IconData(0xeaf6, fontFamily: 'MaterialSymbolsRounded');
  static const IconData expandMore = IconData(0xe5cf, fontFamily: 'MaterialSymbolsRounded');
  static const IconData searchOff = IconData(0xea76, fontFamily: 'MaterialSymbolsRounded');
  static const IconData keyboardArrowDown = IconData(0xe313, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localCafe = IconData(0xeb44, fontFamily: 'MaterialSymbolsRounded');
  static const IconData fastfood = IconData(0xe57a, fontFamily: 'MaterialSymbolsRounded');
  static const IconData lunchDining = IconData(0xea61, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localPizza = IconData(0xe552, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localGroceryStore = IconData(0xe8cc, fontFamily: 'MaterialSymbolsRounded');
  static const IconData directionsCar = IconData(0xeff7, fontFamily: 'MaterialSymbolsRounded');
  static const IconData directionsBus = IconData(0xeff6, fontFamily: 'MaterialSymbolsRounded');
  static const IconData train = IconData(0xe570, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localTaxi = IconData(0xe559, fontFamily: 'MaterialSymbolsRounded');
  static const IconData menuBook = IconData(0xea19, fontFamily: 'MaterialSymbolsRounded');
  static const IconData waterDrop = IconData(0xe798, fontFamily: 'MaterialSymbolsRounded');
  static const IconData checkroom = IconData(0xf19e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData medication = IconData(0xf033, fontFamily: 'MaterialSymbolsRounded');
  static const IconData fitnessCenter = IconData(0xeb43, fontFamily: 'MaterialSymbolsRounded');
  static const IconData contentCut = IconData(0xe14e, fontFamily: 'MaterialSymbolsRounded');
  static const IconData sportsEsports = IconData(0xea28, fontFamily: 'MaterialSymbolsRounded');
  static const IconData musicNote = IconData(0xe405, fontFamily: 'MaterialSymbolsRounded');
  static const IconData pets = IconData(0xe91d, fontFamily: 'MaterialSymbolsRounded');
  static const IconData childCare = IconData(0xeb41, fontFamily: 'MaterialSymbolsRounded');
  static const IconData celebration = IconData(0xea65, fontFamily: 'MaterialSymbolsRounded');
  static const IconData volunteerActivism = IconData(0xea70, fontFamily: 'MaterialSymbolsRounded');
  static const IconData trendingUp = IconData(0xe8e5, fontFamily: 'MaterialSymbolsRounded');
  static const IconData receipt = IconData(0xe8b0, fontFamily: 'MaterialSymbolsRounded');
  static const IconData homeRepairService = IconData(0xf100, fontFamily: 'MaterialSymbolsRounded');
  static const IconData cleaningServices = IconData(0xf0ff, fontFamily: 'MaterialSymbolsRounded');
  static const IconData localLaundryService = IconData(0xe54a, fontFamily: 'MaterialSymbolsRounded');

  /// Icon name (as stored in the database) to glyph.
  static const Map<String, IconData> byName = {
    'home': home,
    'receipt_long': receiptLong,
    'donut_large': donutLarge,
    'account_balance_wallet': accountBalanceWallet,
    'bar_chart': barChart,
    'settings': settings,
    'search': search,
    'more_vert': moreVert,
    'arrow_back': arrowBack,
    'arrow_forward': arrowForward,
    'close': close,
    'add': add,
    'add_card': addCard,
    'add_chart': addChart,
    'filter_list': filterList,
    'calendar_month': calendarMonth,
    'edit': edit,
    'delete': delete,
    'content_copy': contentCopy,
    'push_pin': pushPin,
    'archive': archive,
    'download': download,
    'share': share,
    'refresh': refresh,
    'chevron_right': chevronRight,
    'check': check,
    'groups': groups,
    'north_east': northEast,
    'south_west': southWest,
    'swap_horiz': swapHoriz,
    'tune': tune,
    'autorenew': autorenew,
    'schedule': schedule,
    'done': done,
    'done_all': doneAll,
    'error': error,
    'check_circle': checkCircle,
    'warning': warning,
    'info': info,
    'cloud_done': cloudDone,
    'cloud_off': cloudOff,
    'remove': remove,
    'attach_file': attachFile,
    'send': send,
    'keyboard_double_arrow_down': keyboardDoubleArrowDown,
    'mail': mail,
    'lock': lock,
    'visibility': visibility,
    'visibility_off': visibilityOff,
    'person': person,
    'badge': badge,
    'sell': sell,
    'palette': palette,
    'database': database,
    'help': help,
    'logout': logout,
    'devices': devices,
    'currency_rupee': currencyRupee,
    'public': public,
    'event': event,
    'brightness_auto': brightnessAuto,
    'light_mode': lightMode,
    'dark_mode': darkMode,
    'animation': animation,
    'lock_person': lockPerson,
    'payments': payments,
    'account_balance': accountBalance,
    'smartphone': smartphone,
    'credit_card': creditCard,
    'savings': savings,
    'wallet': wallet,
    'shopping_cart': shoppingCart,
    'restaurant': restaurant,
    'two_wheeler': twoWheeler,
    'local_gas_station': localGasStation,
    'build': build,
    'school': school,
    'bolt': bolt,
    'wifi': wifi,
    'shopping_bag': shoppingBag,
    'medical_services': medicalServices,
    'movie': movie,
    'flight': flight,
    'spa': spa,
    'redeem': redeem,
    'more_horiz': moreHoriz,
    'work': work,
    'laptop_mac': laptopMac,
    'family_restroom': familyRestroom,
    'percent': percent,
    'undo': undo,
    'add_circle': addCircle,
    'category': category,
    'today': today,
    'history': history,
    'notes': notes,
    'balance': balance,
    'expand_more': expandMore,
    'search_off': searchOff,
    'keyboard_arrow_down': keyboardArrowDown,
    'local_cafe': localCafe,
    'fastfood': fastfood,
    'lunch_dining': lunchDining,
    'local_pizza': localPizza,
    'local_grocery_store': localGroceryStore,
    'directions_car': directionsCar,
    'directions_bus': directionsBus,
    'train': train,
    'local_taxi': localTaxi,
    'menu_book': menuBook,
    'water_drop': waterDrop,
    'checkroom': checkroom,
    'medication': medication,
    'fitness_center': fitnessCenter,
    'content_cut': contentCut,
    'sports_esports': sportsEsports,
    'music_note': musicNote,
    'pets': pets,
    'child_care': childCare,
    'celebration': celebration,
    'volunteer_activism': volunteerActivism,
    'trending_up': trendingUp,
    'receipt': receipt,
    'home_repair_service': homeRepairService,
    'cleaning_services': cleaningServices,
    'local_laundry_service': localLaundryService,
  };
}
