/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import { moneyColumn, boolColumn } from '#database/columns'

export class AccountSchema extends BaseModel {
  static $columns = ['archivedAt', 'balance', 'color', 'createdAt', 'creditLimit', 'icon', 'id', 'includeInTotal', 'name', 'openingBalance', 'sortOrder', 'type', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @moneyColumn()
  declare balance: number
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @moneyColumn()
  declare creditLimit: number | null
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: string
  @boolColumn()
  declare includeInTotal: boolean
  @column()
  declare name: string
  @moneyColumn()
  declare openingBalance: number
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BudgetSchema extends BaseModel {
  static $columns = ['alertPercent', 'amount', 'archivedAt', 'color', 'createdAt', 'icon', 'id', 'kind', 'name', 'period', 'rollover', 'sortOrder', 'startDate', 'updatedAt', 'userId'] as const
  $columns = BudgetSchema.$columns
  @column()
  declare alertPercent: number
  @moneyColumn()
  declare amount: number
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare period: string
  @boolColumn()
  declare rollover: boolean
  @column()
  declare sortOrder: number
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class BudgetPeriodOverrideSchema extends BaseModel {
  static $columns = ['amount', 'budgetId', 'createdAt', 'id', 'periodStart', 'updatedAt'] as const
  $columns = BudgetPeriodOverrideSchema.$columns
  @moneyColumn()
  declare amount: number
  @column()
  declare budgetId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare periodStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['archivedAt', 'budgetId', 'color', 'createdAt', 'icon', 'id', 'isDefault', 'name', 'parentId', 'sortOrder', 'type', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare budgetId: string | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: string
  @boolColumn()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: string
}

export class PersonSchema extends BaseModel {
  static $columns = ['archivedAt', 'color', 'createdAt', 'id', 'name', 'note', 'phone', 'updatedAt', 'userId'] as const
  $columns = PersonSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare note: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class RecurringOccurrenceSchema extends BaseModel {
  static $columns = ['createdAt', 'dueDate', 'id', 'recurringRuleId', 'status', 'transactionId', 'updatedAt'] as const
  $columns = RecurringOccurrenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare recurringRuleId: string
  @column()
  declare status: string
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RecurringRuleSchema extends BaseModel {
  static $columns = ['accountId', 'amount', 'autoCreate', 'categoryId', 'createdAt', 'dayOfMonth', 'endDate', 'frequency', 'id', 'interval', 'isActive', 'nextRunAt', 'note', 'startDate', 'toAccountId', 'type', 'updatedAt', 'userId'] as const
  $columns = RecurringRuleSchema.$columns
  @column()
  declare accountId: string
  @moneyColumn()
  declare amount: number
  @boolColumn()
  declare autoCreate: boolean
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfMonth: number | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare interval: number
  @boolColumn()
  declare isActive: boolean
  @column.dateTime()
  declare nextRunAt: DateTime
  @column()
  declare note: string | null
  @column.date()
  declare startDate: DateTime
  @column()
  declare toAccountId: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class TransactionSchema extends BaseModel {
  static $columns = ['accountId', 'adjustmentDirection', 'amount', 'categoryId', 'createdAt', 'date', 'dueDate', 'id', 'note', 'occurrenceDate', 'personId', 'recurringRuleId', 'toAccountId', 'type', 'updatedAt', 'userId'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare accountId: string
  @column()
  declare adjustmentDirection: string | null
  @moneyColumn()
  declare amount: number
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare date: DateTime
  @column.date()
  declare dueDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare note: string | null
  @column.date()
  declare occurrenceDate: DateTime | null
  @column()
  declare personId: string | null
  @column()
  declare recurringRuleId: string | null
  @column()
  declare toAccountId: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'email', 'fullName', 'id', 'locale', 'monthStartDay', 'onboardedAt', 'password', 'theme', 'timezone', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locale: string
  @column()
  declare monthStartDay: number
  @column.dateTime()
  declare onboardedAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare theme: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
